- name: Set Hostname
  ansible.builtin.shell: set-hostname sonarqube

- name: Add SonarQube User
  ansible.builtin.user:
    name: sonarqube

- name: Download SonarQube
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-25.6.0.109173.zip
    dest: /home/sonarqube
    remote_src: yes
    owner: sonarqube
    group: sonarqube

- name: Install Java
  ansible.builtin.dnf:
    name: java-17-openjdk.x86_64
    state: installed

- name: Copy SonarQube service file
  ansible.builtin.template:
    src: sonarqube.service
    dest: /etc/systemd/system/sonarqube.service

- name: Start SonarQube Service
  ansible.builtin.systemd_service:
    name: sonarqube
    state: started
    enabled: yes
