- name: Set Hostname
  ansible.builtin.hostname:
    name: sonarqube

- name: Add SonarQube User
  ansible.builtin.user:
    name: sonarqube
    shell: /bin/bash
    home: /home/sonarqube
    state: present
    create_home: yes

- name: Download SonarQube
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-25.6.0.109173.zip
    dest: /home/sonarqube
    remote_src: yes
    owner: sonarqube
    group: sonarqube
    extra_opts: [--strip-components=1]   # Optional: avoids nested directory

- name: Install Java
  ansible.builtin.dnf:
    name: java-17-openjdk.x86_64
    state: present

- name: Copy SonarQube Service file
  ansible.builtin.template:
    src: sonarqube.service
    dest: /etc/systemd/system/sonarqube.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start SonarQube Service
  ansible.builtin.systemd:
    name: sonarqube
    state: started
    enabled: yes

