- name: Copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install elastic Search
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: Start elasticsearch services
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Install Kibana
  ansible.builtin.dnf:
    name: Kibana
    state: installed

- name: Start kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: started
    enabled: yes

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: copy nginx config.file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: start elasticsearch
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: yes

