- name: Set hostname
  ansible.builtin.shell: set-hostname elasticsearch

- name: Copy Elastic repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Clean yum cache
  ansible.builtin.shell: |
    yum clean all
    yum makecache

- name: Install specific ELK 8.x versions
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - elasticsearch-8.14.0
    - kibana-8.14.0
    - logstash-8.14.0
    - nginx

- name: Copy nginx config
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Enable and start services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - elasticsearch
    - kibana
    - logstash
    - nginx







