- name: Copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Elastic Search
  ansible.builtin.yum:
    name: elasticsearch
    state: installed

- name: Start elasticsearch service
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Install Kibana
  ansible.builtin.yum:
    name: kibana
    state: installed

- name: Start kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: started
    enabled: yes

- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Enable and start Nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: true

- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Reload nginx to apply new config
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded


