- name: Set hostname
  ansible.builtin.shell: hostnamectl set-hostname elasticsearch

- name: Copy Elastic repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Clean yum cache
  ansible.builtin.shell: |
    yum clean all
    yum makecache

- name: Install specific ELK 8.x versions and Nginx
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - elasticsearch-8.14.0
    - kibana-8.14.0
    - logstash-8.14.0
    - nginx

# 🔧 Fix Elasticsearch requirement: vm.max_map_count
- name: Ensure vm.max_map_count is set
  ansible.builtin.sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: yes

- name: Configure Elasticsearch
  ansible.builtin.blockinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      xpack.security.enabled: true
      xpack.security.enrollment.enabled: true
      xpack.security.http.ssl.enabled: false
      network.host: 0.0.0.0
      http.port: 9200

- name: Configure Kibana
  ansible.builtin.blockinfile:
    path: /etc/kibana/kibana.yml
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      server.host: "0.0.0.0"
      server.publicBaseUrl: "http://elasticsearch.tejudevops.online"
      elasticsearch.hosts: ["http://localhost:9200"]
      elasticsearch.username: "elastic"
      elasticsearch.password: "changeme"
      elasticsearch.ssl.verificationMode: none

- name: Copy nginx config
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'

- name: Enable and start services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - elasticsearch
    - kibana
    - logstash
    - nginx






