- name: Copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install elastic Search
  ansible.builtin.dnf:
    name: elasticsearch
    state: restarted



