- name: Copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install elastic Search
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: Start elasticsearch services
  ansible.builtin.systemd.service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Install Kibana
  ansible.builtin.dnf:
    name: Kibana
    state: installed

- name: Start kibana
  ansible.builtin.systemd.service:
    name: kibana
    state: started
    enabled: yes

