groups:
  - name: SaturationAlerts
    rules:
      - alert: MemoryUsedPercentageWarning
        expr: (1-((node_memory_MemFree_bytes+ node_memory_Buffers_bytes+node_memory_Cached_bytes)/ node_memory_MemTotal_bytes)) * 100 >80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Memory Used Percentage in Warning State

      - alert: MemoryUsedPercentageCritical
        expr: (1-((node_memory_MemFree_bytes+ node_memory_Buffers_bytes+node_memory_Cached_bytes)/ node_memory_MemTotal_bytes)) * 100 >90
        for: 1m
        labels:
          severity: Critical
        annotations:
          summary: Memory Used Percentage in Critical State

      - alert: CPUUsedPercentageWarning
        expr: avg by (instance) ((1-(rate(node_cpu_seconds_total{mode="idle"}[5m])))*100)>80
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: CPU Used Percentage in Warning State

      - alert: CPUUsedPercentageCritical
        expr: avg by (instance) ((1-(rate(node_cpu_seconds_total{mode="idle"}[5m])))*100)>90
        for: 1m
        labels:
          severity: Critical
        annotations:
          summary: CPU Used Percentage in Critical State

      - alert: NetworkPackageQueueDropCount
        expr: increase(node_ethtool_pps_allowance_exceeded[5m])
        for: 10m
        labels:
          severity: Critical
        annotations:
          summary: Network Package Queued/Dropped