format_version: 10

pipelines:
  prometheus-terraform:
    group: tools
    label_template: "${COUNT}"
    materials:
      ansible:
        git: https://github.com/Tejaswini-Devops/miscellaneous-code
        branch: main

    stages:
      - dev:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: terraform
                    arguments: [ "init"]
                    working_dir: prometheus
                - exec:
                    command: terraform
                    arguments: [ "apply" ,"auto-approve" ]
                    working_dir: prometheus