format_version: 10

pipelines:

  alb-remove:
    group: tools
    label_template: "${COUNT}"
    materials:
      ansible:
        git: https://github.com/Tejaswini-Devops/miscellaneous-code
        branch: main

    stages:
      - dev:
          fetch_materials: true
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: terraform
                    arguments: [ "init"]

                - exec:
                    command: terraform
                    arguments: [ "delete-alb.sh"]
