- name: Download prometheus setup file
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{prometheus_version}}/prometheus-{{prometheus_version}}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: copy prometheus service file from template
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: copy prometheus config file from template
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-{{prometheus_version}}.linux-amd64/prometheus.yml

- name: Start prometheus service
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Install the latest version of grafana
  ansible.builtin.dnf:
    name: https://dl.grafana.com/enterprise/release/grafana-enterprise-12.0.1-1.x86_64.rpm
    state: installed

- name: Start and enable grafana service
  ansible.builtin.systemd:
    name: grafana-server
    enabled: yes
    state: restarted

